[package]
name = "upc"
description = "USB packet channel (UPC): provides a reliable, packet-based transport over USB."
categories = ["hardware-support", "asynchronous"]
keywords = ["usb", "gadget", "packet", "channel"]
license = "Apache-2.0"
repository = "https://github.com/surban/upc"
authors = ["Sebastian Urban <surban@surban.net>"]
version = "0.1.0"
edition = "2021"
rust-version = "1.73"

[features]
default = []
host = ["rusb"]
device = ["usb-gadget"]

[dependencies]
futures-util = "0.3"
tokio = { version = "1.33", features = ["macros", "rt", "sync"] }
rusb = { version = "0.9", optional = true }
usb-gadget = { version = "0.3", features = ["tokio"], optional = true }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["time"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "env-filter",
    "fmt",
] }
tracing-log = "0.2"
rand_xoshiro = "0.6"
rand = "0.8"

[patch.crates-io]
usb-gadget = { path = "../usb-gadget" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
